import { Inter } from 'next/font/google'
// import '../assets/sass/style.scss'
import '../assets/css/font-icons.css'
import '../assets/css/plugins.css'
import '../assets/css/style.css'
import '../assets/css/responsive.css'


import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Medical Device',
  description: 'Generated by create next app',
  charSet: "utf-8",
  viewPort: "width=device-width, initial-scale=1, shrink-to-fit=no"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <div className='body-wrapper'>
          {children}
        </div>
        <Script src='/assets/js/plugins.js'></Script>
        <Script src='/assets/js/main.js'></Script>
      </body>


    </html>
  )
}
